services:
  - docker
dist: xenial
script:
  - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
  - python3 -VV
  - pip install --upgrade pip
  - pip -V 
before_deploy:
  # install the aws cli
  - python3 -m pip install --user awscli
  # Append exe location to our PATH
  - export PATH=$PATH:$HOME/.local/bin
env:
  global: PATH=/opt/python/3.7.1/bin:$PATH
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: main
