version: "3"
services:
  dev:
    image: "070809985305.dkr.ecr.us-east-2.amazonaws.com/accumulus-redis:latest"
    container_name: "accumulus-production"
    ports: 
      - "8080:8080"
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev:hot
volumes:
  node_modules: {}